# ============================================================
# gen-proto.ps1 — 从 Protocol/proto/game.proto 生成客户端 C# 类型
# 用法：powershell -ExecutionPolicy Bypass -File gen-proto.ps1（在 Client/tools/ 下）
# 前置：protoc.exe 放 tools/protoc/（不入库，下载指引见 Protocol/README.md）
# 产物：Assets/Scripts/Network/Protocol/Generated/Game.cs（入库，禁止手改）
#       命名空间 Dualenigma.V1（由 proto package 决定，不用 base_namespace 免子目录）
# ============================================================
$ErrorActionPreference = "Stop"

$protoc = "$PSScriptRoot/protoc/protoc.exe"
if (-not (Test-Path $protoc)) {
    Write-Error "protoc.exe not found: $protoc"
}

$protoRoot = "$PSScriptRoot/../../Protocol/proto"
$outDir = "$PSScriptRoot/../Assets/Scripts/Network/Protocol/Generated"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

# 不用 base_namespace（会生成 V1/ 子目录）；默认命名空间 = proto package = Dualenigma.V1
& $protoc `
  --proto_path="$protoRoot" `
  --csharp_out="$outDir" `
  --csharp_opt=file_extension=.cs `
  "$protoRoot/game.proto"

if ($LASTEXITCODE -ne 0) { Write-Error "protoc failed (exit $LASTEXITCODE)" }

# 文件头追加"禁止手改"标记
$generated = Join-Path $outDir "Game.cs"
if (Test-Path $generated) {
    $content = [System.IO.File]::ReadAllText($generated)
    $banner = "// <auto-generated> protoc generated (gen-proto.ps1) - DO NOT EDIT. Change Protocol/proto/game.proto and regenerate.`r`n"
    [System.IO.File]::WriteAllText($generated, $banner + $content, (New-Object System.Text.UTF8Encoding $true))
    Write-Host "OK: $generated"
}
